name: Pytest CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Kontrolli kood
        uses: actions/checkout@v3

      - name: Seadista Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installi sõltuvused
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Käivita testid
        run: |
          PYTHONPATH=testing_task_v1-main/pytest-kursus/src pytest testing_task_v1-main/pytest-kursus/tests --maxfail=5 --disable-warnings -q
